from stock_data.contracts.global_market import (
    FRED_TREASURY_YIELD_DAILY, FRED_USD_FX_DAILY, GLOBAL_INDEX_PRICE_DAILY,
    US_TREASURY_SPREAD_DAILY,
)
from stock_data.contracts.kr_equity import (
    KR_EQUITY_MARKET_CAP_DAILY, KR_EQUITY_MASTER, KR_EQUITY_PRICE_DAILY,
    KR_EQUITY_UNIVERSE_DAILY,
    KR_EQUITY_CANONICAL_UNIVERSE_DAILY,
)
from stock_data.contracts.kr_index_daily import KR_INDEX_DAILY
from stock_data.contracts.kr_market import KR_INVESTOR_FLOW_DAILY, KR_MARKET_BREADTH_DAILY
from stock_data.contracts.investor_bridge import INVESTOR_BRIDGE_CONTRACTS
from stock_data.contracts.dividend_observation import DIVIDEND_OBSERVATION_CONTRACTS
from stock_data.contracts.kospi200_derivatives_bridge import (
    KOSPI200_DERIVATIVES_BRIDGE_CONTRACTS,
)
from stock_data.contracts.kospi200_futures_basis import (
    KR_KOSPI200_FUTURES_NEAREST_LISTED_DAILY,
)
from stock_data.contracts.kr_short_selling import (
    KR_SHORT_SELLING_BALANCE_DAILY, KR_SHORT_SELLING_INVESTOR_DAILY,
    KR_SHORT_SELLING_TRADING_DAILY,
)
from stock_data.contracts.data_v1 import DATA_V1_CONTRACTS
from stock_data.contracts.kr_derivatives import KR_DERIVATIVE_CONTRACTS
from stock_data.contracts.kbsec_snapshot import KBSEC_SNAPSHOT_CONTRACTS
from stock_data.contracts.legacy_kospi200 import LEGACY_KOSPI200_CONTRACTS
from stock_data.contracts.legacy_market_investor import LEGACY_MARKET_INVESTOR_CONTRACTS
from stock_data.contracts.tossinvest_historical import TOSSINVEST_HISTORICAL_CONTRACTS
from stock_data.contracts.bok_ecos_treasury import BOK_ECOS_TREASURY_CONTRACTS


CONTRACTS = {contract.name: contract for contract in (
    KR_INDEX_DAILY, KR_EQUITY_PRICE_DAILY, KR_EQUITY_MARKET_CAP_DAILY,
    KR_EQUITY_MASTER, KR_EQUITY_UNIVERSE_DAILY, KR_EQUITY_CANONICAL_UNIVERSE_DAILY,
    KR_INVESTOR_FLOW_DAILY, KR_MARKET_BREADTH_DAILY,
    GLOBAL_INDEX_PRICE_DAILY, FRED_TREASURY_YIELD_DAILY, FRED_USD_FX_DAILY,
    US_TREASURY_SPREAD_DAILY,
    KR_SHORT_SELLING_TRADING_DAILY, KR_SHORT_SELLING_BALANCE_DAILY,
    KR_SHORT_SELLING_INVESTOR_DAILY,
    *DATA_V1_CONTRACTS,
    *KR_DERIVATIVE_CONTRACTS,
    *KBSEC_SNAPSHOT_CONTRACTS,
    *LEGACY_KOSPI200_CONTRACTS,
    *LEGACY_MARKET_INVESTOR_CONTRACTS,
    *INVESTOR_BRIDGE_CONTRACTS,
    *DIVIDEND_OBSERVATION_CONTRACTS,
    *KOSPI200_DERIVATIVES_BRIDGE_CONTRACTS,
    KR_KOSPI200_FUTURES_NEAREST_LISTED_DAILY,
    *TOSSINVEST_HISTORICAL_CONTRACTS,
    *BOK_ECOS_TREASURY_CONTRACTS,
)}

if len(CONTRACTS) != 16 + len(DATA_V1_CONTRACTS) + len(KR_DERIVATIVE_CONTRACTS) + len(KBSEC_SNAPSHOT_CONTRACTS) + len(LEGACY_KOSPI200_CONTRACTS) + len(LEGACY_MARKET_INVESTOR_CONTRACTS) + len(INVESTOR_BRIDGE_CONTRACTS) + len(DIVIDEND_OBSERVATION_CONTRACTS) + len(KOSPI200_DERIVATIVES_BRIDGE_CONTRACTS) + len(TOSSINVEST_HISTORICAL_CONTRACTS) + len(BOK_ECOS_TREASURY_CONTRACTS):
    raise RuntimeError("duplicate Dataset Contract name")
