from stock_data.contracts.global_market import (
    FRED_TREASURY_YIELD_DAILY, FRED_USD_FX_DAILY, FRED_VIX_DAILY, GLOBAL_INDEX_PRICE_DAILY,
    GLOBAL_COMMODITY_FUTURES_DAILY,
    US_TREASURY_SPREAD_DAILY, US_VIX_TERM_STRUCTURE_DAILY,
)
from stock_data.contracts.global_etf import GLOBAL_ETF_PRICE_DAILY
from stock_data.contracts.market_60m import MARKET_PRICE_60M_OBSERVATION
from stock_data.contracts.market_15m import MARKET_PRICE_15M_OBSERVATION
from stock_data.contracts.kr_equity import (
    KR_EQUITY_MARKET_CAP_DAILY, KR_EQUITY_MASTER, KR_EQUITY_PRICE_DAILY,
    KR_EQUITY_UNIVERSE_DAILY,
    KR_EQUITY_CANONICAL_UNIVERSE_DAILY,
)
from stock_data.contracts.kr_equity_provisional import (
    KR_EQUITY_PRICE_PROVISIONAL_DAILY,
)
from stock_data.contracts.kr_equity_investor_flow import (
    KR_EQUITY_INVESTOR_FLOW_DAILY,
)
from stock_data.contracts.kr_index_daily import KR_INDEX_DAILY
from stock_data.contracts.kr_market import KR_INVESTOR_FLOW_DAILY, KR_MARKET_BREADTH_DAILY
from stock_data.contracts.investor_bridge import INVESTOR_BRIDGE_CONTRACTS
from stock_data.contracts.dividend_observation import DIVIDEND_OBSERVATION_CONTRACTS
from stock_data.contracts.kospi200_derivatives_bridge import (
    KOSPI200_DERIVATIVES_BRIDGE_CONTRACTS,
)
from stock_data.contracts.kospi200_futures_basis import (
    KR_KOSPI200_FUTURES_NEAREST_LISTED_DAILY,
)
from stock_data.contracts.kospi200_option_walls import KR_KOSPI200_OPTION_WALLS_DAILY
from stock_data.contracts.kospi200_index_daily import KR_KOSPI200_INDEX_DAILY
from stock_data.contracts.kospi200_constituent_breadth import (
    KOSPI200_CONSTITUENT_BREADTH_CONTRACTS,
)
from stock_data.contracts.vkospi_daily import KR_VKOSPI_DAILY
from stock_data.contracts.kr_short_selling import (
    KR_SHORT_SELLING_BALANCE_DAILY, KR_SHORT_SELLING_INVESTOR_DAILY,
    KR_SHORT_SELLING_TRADING_DAILY,
)
from stock_data.contracts.data_v1 import DATA_V1_CONTRACTS
from stock_data.contracts.kr_derivatives import KR_DERIVATIVE_CONTRACTS
from stock_data.contracts.kbsec_snapshot import KBSEC_SNAPSHOT_CONTRACTS
from stock_data.contracts.legacy_kospi200 import LEGACY_KOSPI200_CONTRACTS
from stock_data.contracts.legacy_market_investor import LEGACY_MARKET_INVESTOR_CONTRACTS
from stock_data.contracts.tossinvest_historical import TOSSINVEST_HISTORICAL_CONTRACTS
from stock_data.contracts.bok_ecos_treasury import BOK_ECOS_TREASURY_CONTRACTS
from stock_data.contracts.bok_ecos_fx import BOK_ECOS_FX_CONTRACTS
from stock_data.contracts.stock_issuance_observation import (
    STOCK_ISSUANCE_OBSERVATION_CONTRACTS,
)
from stock_data.contracts.krx_derivatives_investor import (
    KRX_DERIVATIVES_INVESTOR_CONTRACTS,
)
from stock_data.contracts.ls_t8428 import LS_T8428_CONTRACTS
from stock_data.contracts.kr_etf import KR_ETF_CONTRACTS


CONTRACTS = {contract.name: contract for contract in (
    KR_INDEX_DAILY, KR_EQUITY_PRICE_DAILY, KR_EQUITY_PRICE_PROVISIONAL_DAILY,
    KR_EQUITY_INVESTOR_FLOW_DAILY,
    KR_EQUITY_MARKET_CAP_DAILY,
    KR_EQUITY_MASTER, KR_EQUITY_UNIVERSE_DAILY, KR_EQUITY_CANONICAL_UNIVERSE_DAILY,
    KR_INVESTOR_FLOW_DAILY, KR_MARKET_BREADTH_DAILY,
    GLOBAL_INDEX_PRICE_DAILY, GLOBAL_COMMODITY_FUTURES_DAILY, GLOBAL_ETF_PRICE_DAILY,
    MARKET_PRICE_60M_OBSERVATION, MARKET_PRICE_15M_OBSERVATION,
    FRED_TREASURY_YIELD_DAILY, FRED_USD_FX_DAILY, FRED_VIX_DAILY,
    US_TREASURY_SPREAD_DAILY, US_VIX_TERM_STRUCTURE_DAILY,
    KR_SHORT_SELLING_TRADING_DAILY, KR_SHORT_SELLING_BALANCE_DAILY,
    KR_SHORT_SELLING_INVESTOR_DAILY,
    *DATA_V1_CONTRACTS,
    *KR_DERIVATIVE_CONTRACTS,
    *KBSEC_SNAPSHOT_CONTRACTS,
    *LEGACY_KOSPI200_CONTRACTS,
    *LEGACY_MARKET_INVESTOR_CONTRACTS,
    *INVESTOR_BRIDGE_CONTRACTS,
    *DIVIDEND_OBSERVATION_CONTRACTS,
    *KOSPI200_DERIVATIVES_BRIDGE_CONTRACTS,
    KR_KOSPI200_FUTURES_NEAREST_LISTED_DAILY,
    KR_KOSPI200_OPTION_WALLS_DAILY,
    KR_KOSPI200_INDEX_DAILY,
    *KOSPI200_CONSTITUENT_BREADTH_CONTRACTS,
    KR_VKOSPI_DAILY,
    *TOSSINVEST_HISTORICAL_CONTRACTS,
    *BOK_ECOS_TREASURY_CONTRACTS,
    *BOK_ECOS_FX_CONTRACTS,
    *STOCK_ISSUANCE_OBSERVATION_CONTRACTS,
    *KRX_DERIVATIVES_INVESTOR_CONTRACTS,
    *LS_T8428_CONTRACTS,
    *KR_ETF_CONTRACTS,
)}

if len(CONTRACTS) != 27 + len(DATA_V1_CONTRACTS) + len(KR_DERIVATIVE_CONTRACTS) + len(KBSEC_SNAPSHOT_CONTRACTS) + len(LEGACY_KOSPI200_CONTRACTS) + len(LEGACY_MARKET_INVESTOR_CONTRACTS) + len(INVESTOR_BRIDGE_CONTRACTS) + len(DIVIDEND_OBSERVATION_CONTRACTS) + len(KOSPI200_DERIVATIVES_BRIDGE_CONTRACTS) + len(TOSSINVEST_HISTORICAL_CONTRACTS) + len(BOK_ECOS_TREASURY_CONTRACTS) + len(BOK_ECOS_FX_CONTRACTS) + len(STOCK_ISSUANCE_OBSERVATION_CONTRACTS) + len(KRX_DERIVATIVES_INVESTOR_CONTRACTS) + len(LS_T8428_CONTRACTS) + len(KOSPI200_CONSTITUENT_BREADTH_CONTRACTS) + len(KR_ETF_CONTRACTS):
    raise RuntimeError("duplicate Dataset Contract name")
